name: 'Sync repository'
description: 'Sync repository to Gitee.'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  github-repo:
    description: 'git@gitee.com:ziaostudio/gocms.git'
    required: true
    default: ''
  gitee-repo:
    description: 'git@gitee.com:ziaostudio/gocms.git'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-repo }}
    - ${{ inputs.gitee-repo }}
